### ISSUE TITLE
[LAB] Style Meeting Minutes Page

### ISSUE THREAD

**Issue by marklcrns** [marklcrns/sp23-cse110-lab3#2]
# Task Goal

Styling the Meeting Minutes page

## Description

Create a CSS for Meeting MInutes

## TODO

- [ ] Create styles.css
- [ ] Link styles.css in index.html
- [ ] Finish designing index.html with CSS
