### ISSUE TITLE
[LAB] Submit Lab 3

### ISSUE THREAD

**Issue by marklcrns** [marklcrns/sp23-cse110-lab3#3]
# Task Goal

Submit Lab 3 in Canvas

## Description

Lab 3 Canvas submission

## TODO

- [ ] Make sure README.md is included containing the GitHub pages link
- [ ] Make sure the standup notes template is completed
- [ ] Style HTML with styles.css

**Comment by marklcrns** [comment]
Done
